server:
  port: 8090
spring:
  application:
    name: asgc-sys-consumer
  swagger:
    base-package: com.asgc

dubbo:
  application:
    name: dubbo-sys-test-consumer
  registry:
    address: N/A
  reference:
    id: demoService
    interface: com.asgc.sys.facade.test.service.DemoService
    url: dubbo://localhost:20880
    version: 1.0.0
    timeout: 10000
  reference:
    id: demoService2
    interface: com.asgc.sys.facade.test.service.DemoService2
    url: dubbo://localhost:20880
    version: 1.0.0
    timeout: 10000
